export const OPENAI_MODELS = {
  GPT4: 'gpt-4o',
  GPT4_MINI: 'gpt-4o-mini-2024-07-18'
} as const;

export const RETRY_CONFIG = {
  MAX_ATTEMPTS: 3,
  DELAY_MS: 1000,
  BACKOFF_FACTOR: 1.5
} as const;

export const ERROR_CODES = {
  CONFIGURATION: 'CONFIGURATION_ERROR',
  ASSISTANT: 'ASSISTANT_ERROR',
  THREAD: 'THREAD_ERROR',
  MESSAGE: 'MESSAGE_ERROR',
  ORCHESTRATION: 'ORCHESTRATION_ERROR',
  VALIDATION: 'VALIDATION_ERROR'
} as const;